# Generated by Django 4.2 on 2024-06-12 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField(unique=True)),
                ('product_code', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('total_stock', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Products',
                'ordering': ('-created_date', 'product_id'),
                'unique_together': {('product_code', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app.products')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
                'db_table': 'Variant',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_variants', to='app.products')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_variants', to='app.variant')),
            ],
            options={
                'verbose_name': 'sub variant',
                'verbose_name_plural': 'sub variants',
                'db_table': 'SubVariant',
                'ordering': ['name'],
                'unique_together': {('product', 'variant', 'name')},
            },
        ),
    ]
